### ISSUE TITLE
Worldline payment getway flutter sdk

### ISSUE THREAD

**Issue by akshat56121** [wl-online-payments-direct/sdk-client-android-example#1]
I want to Know that the worldline payment getway is available for flutter android platform?

**Comment by worldline-direct-support-team** [comment]
Hello akshat56121,

At the moment we do not offer a solution that is immediately compatible with Flutter. However, you should be able to use our native Android SDK, which you can find here: https://github.com/wl-online-payments-direct/sdk-client-android 

Kind regards,
Worldline support
